package com.example.android.typer;

import java.util.StringTokenizer;

public class data {
    public final String basic_data = "Certainly$" + "Good afternoon.$" + "Good evening sir.$" + "Good Luck.$" + "Good morning.$" + "Great.$" + "Happy Birthday.$" + "Have a good trip.$" +
            "Hello.$" + "ability$" + "able$" + "about$" + "above$" + "accept$" + "according$" + "account$" + "across$" + "act$" + "action$" + "activity$" + "actually$" + "add$" + "address$" + "administration$" + "admit$" + "adult$" + "affect$" +
            "after$" + "again$" + "against$" + "age$" + "agency$" + "agent$" + "ago$" + "agree$" + "agreement$" + "ahead$" + "air$" + "all$" + "allow$" + "almost$" + "alone$" + "along$" + "already$" + "also$" + "although$" + "always$" + "American$" + "among$" + "amount$" + "analysis$" + "and$" +
            "animal$" + "another$" + "answer$" + "any$" + "anyone$" + "anything$" + "appear$" + "apply$" + "approach$" + "area$" + "argue$" + "arm$" + "around$" + "arrive$" + "art$" + "article$" + "artist$" + "as$" + "ask$" + "assume$" +
            "at$" + "attack$" + "attention$" + "attorney$" + "audience$" + "author$" + "authority$" + "available$" + "avoid$" + "away$" + "baby$" + "back$" + "bad$" + "bag$" + "ball$" + "bank$" + "bar$" + "base$" + "be$" + "beat$" + "beautiful$" + "because$" + "become$" + "bed$" + "before$" + "begin$" + "behavior$" + "behind$" + "believe$" + "benefit$" + "best$" + "better$" + "between$" + "beyond$" + "big$" +
            "bill$" + "billion$" + "bit$" + "black$" + "blood$" + "blue$" + "board$" + "body$" + "book$" + "born$" + "both$" + "box$" + "boy$" + "break$" + "bring$" + "brother$" + "budget$" + "build$" + "building$" + "business$" + "but$" + "buy$" + "by$" + "call$" + "camera$" + "campaign$" + "can$" +
            "cancer$" + "candidate$" + "capital$" + "car$" + "card$" + "care$" + "career$" + "carry$" + "case$" + "catch$" + "cause$" + "cell$" + "center$" + "central$" + "century$" + "certain$" + "certainly$" + "chair$" + "challenge$" + "chance$" + "change$" + "character$" + "charges" +
            "check$" + "child$" + "choice$" + "choose$" + "church$" + "citizen$" + "city$" + "civil$" + "claim$" + "class$" + "clear$" + "clearly$" + "close$" + "coach$" + "cold$" + "collection$" + "college$" + "color$" + "come$" + "commercial$" + "common$" + "community$" + "company$" + "compare$" + "computer$"+"concentrate"+ "concentration"+
            "concept"+ "concern"+
            "concerned"+
            "concert"+ "conclude"+ "conclusion"+ "concrete"+ "condition"+
            "conduct"+ "conference"+
            "confidence"+
            "confident"+
            "confirm"+
            "conflict"+ "confront"+ "confusion"+ "Congress"+ "congressional"+
            "connect"+
            "connection"+
            "consciousness"+ "consensus"+ "consequence"+ "conservative"+ "consider"+ "considerable"+ "consideration"+ "consist"+ "consistent"+ "constant"+ "constantly"+ "constitute"+ "constitutional"+ "construct"+ "construction"+ "consultant"+ "consume"+ "consumer"+
            "consumption"+
            "contact"+
            "contain"+ "container"+ "contemporary"+ "content"+
            "contest"+
            "context"+
            "continue"+
            "continued"+
            "contract"+
            "contrast"+
            "contribute"+
            "contribution"+
            "control"+
            "controversial"+
            "controversy"+
            "convention"+
            "conventional"+
            "conversation"+
            "convert"+
            "conviction"+
            "convince"+
            "cook"+
            "cookie"+
            "cooking"+
            "cool"+
            "cooperation"+
            "cop"+
            "cope"+
            "copy"+
            "core"+
            "corn"+
            "corner"+
            "corporate"+
            "corporation"+
            "correct"+
            "correspondent"+
            "cost"+
            "cotton"+
            "couch"+
            "could"+
            "council"+
            "counselor"+
            "count"+
            "counter"+
            "country"+
            "county"+
            "couple"+
            "courage"+
            "course"+
            "court"+
            "cousin"+
            "cover"+
            "coverage"+
            "cow"+
            "crack"+
            "craft"+
            "crash"+
            "crazy"+
            "cream"+
            "create"+
            "creation"+
            "creative"+
            "creature"+
            "credit"+
            "crew"+
            "crime"+
            "criminal"+
            "crisis"+
            "criteria"+
            "critic"+
            "critical"+
            "criticism"+
            "criticize"+
            "crop"+
            "cross"+
            "crowd"+
            "crucial"+
            "cry"+
            "cultural"+
            "culture"+
            "cup"+
            "curious"+
            "current"+
            "currently"+
            "curriculum"+
            "custom"+
            "customer"+
            "cut"+
            "cycle"+
            "dad"+
            "daily"+
            "damage"+
            "dance"+
            "danger"+
            "dangerous"+
            "dare"+
            "dark"+
            "darkness"+
            "data"+
            "date"+
            "daughter"+
            "day"+
            "dead"+
            "deal"+
            "dealer"+
            "dear"+
            "death"+
            "debate"+
            "debt"+
            "decade"+
            "decide"+
            "decision"+
            "deck"+
            "declare"+
            "decline"+
            "decrease"+
            "deep"+
            "deeply"+
            "deer"+
            "defeat"+
            "defend"+
            "defendant"+
            "defense"+
            "defensive"+
            "deficit"+
            "define"+
            "definitely"+
            "definition"+
            "degree"+
            "delay"+
            "deliver"+
            "delivery"+
            "demand"+
            "democracy"+
            "Democrat"+
            "democratic"+
            "demonstrate"+
            "demonstration"+
            "deny"+
            "department"+
            "depend"+
            "dependent"+
            "depending"+
            "depict"+
            "depression"+
            "depth"+
            "deputy"+
            "derive"+
            "describe"+
            "description"+
            "desert"+
            "deserve"+
            "design"+
            "designer"+
            "desire"+
            "desk"+
            "desperate"+
            "despite"+
            "destroy"+
            "destruction"+
            "detail"+
            "detailed"+
            "detect"+
            "determine"+
            "develop"+
            "developing"+
            "development"+
            "device"+
            "devote"+
            "dialogue"+
            "die"+
            "diet"+
            "differ"+
            "difference"+
            "different"+
            "differently"+
            "difficult"+
            "difficulty"+
            "dig"+
            "digital"+
            "dimension"+
            "dining"+
            "dinner"+
            "direct"+
            "direction"+
            "directly"+
            "director"+
            "dirt"+
            "dirty"+
            "disability"+
            "disagree"+
            "disappear"+
            "disaster"+
            "discipline"+
            "discourse"+
            "discover"+
            "discovery"+
            "discrimination"+
            "discuss"+
            "discussion"+
            "disease"+
            "dish"+
            "dismiss"+
            "disorder"+
            "display"+
            "dispute"+
            "distance"+
            "distant"+
            "distinct"+
            "distinction"+
            "distinguish"+
            "distribute"+
            "distribution"+
            "district"+
            "diverse"+
            "diversity"+
            "divide"+
            "division"+
            "divorce"+
            "DNA"+
            "do"+
            "doctor"+
            "document"+
            "dog"+
            "domestic"+
            "dominant"+
            "dominate"+
            "door"+
            "double"+
            "doubt"+
            "down"+
            "downtown"+
            "dozen"+
            "draft"+
            "drag"+
            "drama"+
            "dramatic"+
            "dramatically"+
            "draw"+
            "drawing"+
            "dream"+
            "dress"+
            "drink"+
            "drive"+
            "driver"+
            "drop"+
            "drug"+
            "dry"+
            "due"+
            "during"+
            "dust"+
            "duty"+
            "each"+
            "eager"+
            "ear"+
            "early"+
            "earn"+
            "earnings"+
            "earth"+
            "ease"+
            "easily"+
            "east"+
            "eastern"+
            "easy"+
            "eat"+
            "economic"+
            "economics"+
            "economist"+
            "economy"+
            "edge"+
            "edition"+
            "editor"+
            "educate"+
            "education"+
            "educational"+
            "educator"+
            "effect"+
            "effective"+
            "effectively"+
            "efficiency"+
            "efficient"+
            "effort"+
            "egg"+
            "eight"+
            "either"+
            "elderly"+
            "elect"+
            "election"+
            "electric"+
            "electricity"+
            "electronic"+
            "element"+
            "elementary"+
            "eliminate"+
            "elite"+
            "else"+
            "elsewhere"+
            "e-mail"+
            "embrace"+
            "emerge"+
            "emergency"+
            "emission"+
            "emotion"+
            "emotional"+
            "emphasis"+
            "emphasize"+
            "employ"+
            "employee"+
            "employer"+
            "employment"+
            "empty"+
            "enable"+
            "encounter"+
            "encourage"+
            "end"+
            "enemy"+
            "energy"+
            "enforcement"+
            "engage"+
            "engine"+
            "engineer"+
            "engineering"+
            "English"+
            "enhance"+
            "enjoy"+
            "enormous"+
            "enough"+
            "ensure"+
            "enter"+
            "enterprise"+
            "entertainment"+
            "entire"+
            "entirely"+
            "entrance"+
            "entry"+
            "environment"+
            "environmental"+
            "episode"+
            "equal"+
            "equally"+
            "equipment"+
            "era"+
            "error"+
            "escape"+
            "especially"+
            "essay"+
            "essential"+
            "essentially"+
            "establish"+
            "establishment"+
            "estate"+
            "estimate"+
            "etc"+
            "ethics"+
            "ethnic"+
            "European"+
            "evaluate"+
            "evaluation"+
            "even"+
            "evening"+
            "event"+
            "eventually"+
            "ever"+
            "every"+
            "everybody"+
            "everyday"+
            "everyone"+
            "everything"+
            "everywhere"+
            "evidence"+
            "evolution"+
            "evolve"+
            "exact"+
            "exactly"+
            "examination"+
            "examine"+
            "example"+
            "exceed"+
            "excellent"+
            "except"+
            "exception"+
            "exchange"+
            "exciting"+
            "executive"+
            "exercise"+
            "exhibit"+
            "exhibition"+
            "exist"+
            "existence"+
            "existing"+
            "expand"+
            "expansion"+
            "expect"+
            "expectation"+
            "expense"+
            "expensive"+
            "experience"+
            "experiment"+
            "expert"+
            "explain"+
            "explanation"+
            "explode"+
            "explore"+
            "explosion"+
            "expose"+
            "exposure"+
            "express"+
            "expression"+
            "extend"+
            "extension"+
            "extensive"+
            "extent"+
            "external"+
            "extra"+
            "extraordinary"+
            "extreme"+
            "extremely"+
            "eye"+
            "fabric"+
            "face"+
            "facility"+
            "fact"+
            "factor"+
            "factory"+
            "faculty"+
            "fade"+
            "fail"+
            "failure"+"fair"+
            "fairly"+
            "faith"+
            "fall"+
            "false"+
            "familiar"+
            "family"+
            "famous"+
            "fan"+
            "fantasy"+
            "far"+
            "farm"+
            "farmer"+
            "fashion"+
            "fast"+
            "fat"+
            "fate"+
            "father"+
            "fault"+
            "favor"+
            "favorite"+
            "fear"+
            "feature"+
            "federal"+
            "fee"+
            "feed"+
            "feel"+
            "feeling"+
            "fellow"+
            "female"+
            "fence"+
            "few"+
            "fewer"+
            "fiber"+
            "fiction"+
            "field"+
            "fifteen"+
            "fifth"+
            "fifty"+
            "fight"+
            "fighter"+
            "fighting"+
            "figure"+
            "file"+
            "fill"+
            "film"+
            "final"+
            "finally"+
            "finance"+
            "financial"+
            "find"+
            "finding"+
            "fine"+
            "finger"+
            "finish"+
            "fire"+
            "firm"+
            "first"+
            "fish"+
            "fishing"+
            "fit"+
            "fitness"+
            "five"+
            "fix"+
            "flag"+
            "flame"+
            "flat"+
            "flavor"+
            "flee"+
            "flesh"+
            "flight"+
            "float"+
            "floor"+
            "flow"+
            "flower"+
            "fly"+
            "focus"+
            "folk"+
            "follow"+
            "following"+
            "food"+
            "foot"+
            "football"+
            "for"+
            "force"+
            "foreign"+
            "forest"+
            "forever"+
            "forget"+
            "form"+
            "formal"+
            "formation"+
            "former"+
            "formula"+
            "forth"+
            "fortune"+
            "forward"+
            "found"+
            "foundation"+
            "founder"+
            "four"+
            "fourth"+
            "frame"+
            "framework"+
            "free"+
            "freedom"+
            "freeze"+
            "French"+
            "frequency"+
            "frequent"+
            "frequently"+
            "fresh"+
            "friend"+
            "friendly"+
            "friendship"+
            "from"+
            "front"+
            "fruit"+
            "frustration"+
            "fuel"+
            "full"+
            "fully"+
            "fun"+
            "function"+
            "fund"+
            "fundamental"+
            "funding"+
            "funeral"+
            "funny"+
            "furniture"+
            "furthermore"+
            "future"+
            "gain"+
            "galaxy"+
            "gallery"+
            "game"+
            "gang"+
            "gap"+
            "garage"+
            "garden"+
            "garlic"+
            "gas"+
            "gate"+
            "gather"+
            "gay"+
            "gaze"+
            "gear"+
            "gender"+
            "gene"+
            "general"+
            "generally"+
            "generate"+
            "generation"+
            "genetic"+
            "gentleman"+
            "gently"+
            "German"+
            "gesture"+
            "get"+
            "ghost"+
            "giant"+
            "gift"+
            "gifted"+
            "girl"+
            "girlfriend"+
            "give"+
            "given"+
            "glad"+
            "glance"+
            "glass"+
            "global"+
            "glove"+
            "go"+
            "goal"+
            "God"+
            "gold"+
            "golden"+
            "golf"+
            "good"+
            "government"+
            "governor"+
            "grab"+
            "grade"+
            "gradually"+
            "graduate"+
            "grain"+
            "grand"+
            "grandfather"+
            "grandmother"+
            "grant"+
            "grass"+
            "grave"+
            "gray"+
            "great"+
            "greatest"+
            "green"+
            "grocery"+
            "ground"+
            "group"+
            "grow"+
            "growing"+
            "growth"+
            "guarantee"+
            "guard"+
            "guess"+
            "guest"+
            "guide"+
            "guideline"+
            "guilty"+
            "gun"+
            "guy"+
            "habit"+"habitat"+
            "hair"+
            "half"+
            "hall"+
            "hand"+
            "handful"+
            "handle"+
            "hang"+
            "happen"+
            "happy"+
            "hard"+
            "hardly"+
            "hat"+
            "hate"+
            "have"+
            "he"+
            "head"+
            "headline"+
            "headquarters"+
            "health"+
            "healthy"+
            "hear"+
            "hearing"+
            "heart"+
            "heat"+
            "heaven"+
            "heavily"+
            "heavy"+
            "heel"+
            "height"+
            "helicopter"+
            "hell"+
            "hello"+
            "help"+
            "helpful"+
            "her"+
            "here"+
            "heritage"+
            "hero"+
            "herself"+
            "hey"+
            "hi"+
            "hide"+
            "high"+
            "highlight"+
            "highly"+
            "highway"+
            "hill"+
            "him"+
            "himself"+
            "hip"+
            "hire"+
            "his"+
            "historian"+
            "historic"+
            "historical"+
            "history"+
            "hit"+
            "hold"+
            "hole"+
            "holiday"+
            "holy"+
            "home"+
            "homeless"+
            "honest"+
            "honey"+
            "honor"+
            "hope"+
            "horizon"+
            "horror"+
            "horse"+
            "hospital"+
            "host"+
            "hot"+
            "hotel"+
            "hour"+
            "house"+
            "household"+
            "housing"+
            "how"+
            "however"+
            "huge"+
            "human"+
            "humor"+
            "hundred"+
            "hungry"+
            "hunter"+
            "hunting"+
            "hurt"+
            "husband"+
            "hypothesis"+
            "I"+
            "ice"+
            "idea"+
            "ideal"+
            "identification"+
            "identify"+
            "identity"+
            "ie"+
            "if"+
            "ignore"+
            "ill"+
            "illegal"+
            "illness"+
            "illustrate"+
            "image"+
            "imagination"+
            "imagine"+
            "immediate"+
            "immediately"+
            "immigrant"+
            "immigration"+
            "impact"+
            "implement"+
            "implication"+
            "imply"+
            "importance"+
            "important"+
            "impose"+
            "impossible"+
            "impress"+
            "impression"+
            "impressive"+
            "improve"+
            "improvement"+
            "in"+
            "incentive"+
            "incident"+
            "include"+
            "including"+
            "income"+
            "incorporate"+
            "increase"+
            "increased"+
            "increasing"+
            "increasingly"+
            "incredible"+
            "indeed"+
            "independence"+
            "independent"+
            "index"+
            "Indian"+
            "indicate"+
            "indication"+
            "individual"+
            "industrial"+
            "industry"+
            "infant"+
            "infection"+
            "inflation"+
            "influence"+
            "inform"+
            "information"+
            "ingredient"+
            "initial"+
            "initially"+
            "initiative"+
            "injury"+
            "inner"+
            "innocent"+
            "inquiry"+
            "inside"+
            "insight"+
            "insist"+
            "inspire"+
            "install"+
            "instance"+
            "instead"+
            "institution"+
            "institutional"+
            "instruction"+
            "instructor"+
            "instrument"+
            "insurance"+
            "intellectual"+
            "intelligence"+
            "intend"+
            "intense"+
            "intensity"+
            "intention"+
            "interaction"+
            "interest"+
            "interested"+
            "interesting"+
            "internal"+
            "international"+
            "Internet"+
            "interpret"+
            "interpretation"+
            "intervention"+
            "interview"+
            "into"+
            "introduce"+
            "introduction"+
            "invasion"+
            "invest"+
            "investigate"+
            "investigation"+
            "investigator"+
            "investment"+
            "investor"+
            "invite"+
            "involve"+
            "involved"+
            "involvement"+
            "Iraqi"+
            "Irish"+
            "iron"+
            "Islamic"+
            "island"+
            "Israeli"+
            "issue"+
            "it"+
            "Italian"+
            "item"+
            "its"+
            "itself"+
            "jacket"+
            "jail"+
            "Japanese"+
            "jet"+
            "Jew"+
            "Jewish"+
            "job"+
            "join"+
            "joint"+
            "joke"+
            "journal"+
            "journalist"+
            "journey"+
            "joy"+
            "judge"+
            "judgment"+
            "juice"+
            "jump"+
            "junior"+
            "jury"+
            "just"+
            "justice"+
            "justify"+
            "keep"+
            "key"+
            "kick"+
            "kid"+
            "kill"+
            "killer"+
            "killing"+
            "kind"+
            "king"+
            "kiss"+
            "kitchen"+
            "knee"+
            "knife"+
            "knock"+
            "know"+
            "knowledge"+
            "lab"+
            "label"+
            "labor"+
            "laboratory"+
            "lack"+
            "lady"+
            "lake"+
            "land"+
            "landscape"+
            "language"+
            "lap"+
            "large"+
            "largely"+
            "last"+
            "late"+
            "later"+
            "Latin"+
            "latter"+
            "laugh"+
            "launch"+
            "law"+
            "lawn"+
            "lawsuit"+
            "lawyer"+
            "lay"+
            "layer"+
            "lead"+
            "leader"+
            "leadership"+
            "leading"+
            "leaf"+
            "league"+
            "lean"+
            "learn"+
            "learning"+
            "least"+
            "leather"+
            "leave"+
            "left"+
            "leg"+
            "legacy"+
            "legal"+
            "legend"+
            "legislation"+
            "legitimate"+
            "lemon"+
            "length"+
            "less"+
            "lesson"+
            "let"+
            "letter"+
            "level"+
            "liberal"+
            "library"+
            "license"+
            "lie"+
            "life"+
            "lifestyle"+
            "lifetime"+
            "lift"+
            "light"+
            "like"+
            "likely"+
            "limit"+
            "limitation"+
            "limited"+
            "line"+
            "link"+
            "lip"+
            "list"+
            "listen"+
            "literally"+
            "literary"+
            "literature"+
            "little"+
            "live"+
            "living"+
            "load"+
            "loan"+
            "local"+
            "locate"+
            "location"+
            "lock"+
            "long"+
            "long-term"+
            "look"+
            "loose"+
            "lose"+
            "loss"+
            "lost"+
            "lot"+
            "lots"+
            "loud"+
            "love"+
            "lovely"+
            "lover"+
            "low"+
            "lower"+
            "luck"+
            "lucky"+
            "lunch"+
            "lung"+
            "machine"+
            "mad"+
            "magazine"+
            "mail"+
            "main"+
            "mainly"+
            "maintain"+
            "maintenance"+
            "major"+
            "majority"+
            "make"+
            "maker"+
            "makeup"+
            "male"+
            "mall"+
            "man"+
            "manage"+
            "management"+
            "manager"+
            "manner"+
            "manufacturer"+
            "manufacturing"+
            "many"+
            "map"+
            "margin"+
            "mark"+
            "market"+
            "marketing"+
            "marriage"+
            "married"+
            "marry"+
            "mask"+
            "mass"+
            "massive"+
            "master"+
            "match"+
            "material"+
            "math"+
            "matter"+
            "may"+
            "maybe"+
            "mayor"+
            "me"+
            "meal"+
            "mean"+
            "meaning"+
            "meanwhile"+
            "measure"+
            "measurement"+
            "meat"+
            "mechanism"+
            "media"+
            "medical"+
            "medication"+
            "medicine"+
            "medium"+
            "meet"+
            "meeting"+
            "member"+
            "membership"+
            "memory"+
            "mental"+
            "mention"+
            "menu"+
            "mere"+
            "merely"+
            "mess"+
            "message"+
            "metal"+
            "meter"+
            "method"+
            "Mexican"+
            "middle"+
            "might"+
            "military"+
            "milk"+
            "million"+
            "mind"+
            "mine"+
            "minister"+
            "minor"+
            "minority"+
            "minute"+
            "miracle"+
            "mirror"+
            "miss"+
            "missile"+
            "mission"+
            "mistake"+
            "mix"+
            "mixture"+
            "mm-hmm"+
            "mode"+
            "model"+
            "moderate"+
            "modern"+
            "modest"+
            "mom"+
            "moment"+
            "money"+
            "monitor"+
            "month"+
            "mood"+
            "moon"+
            "moral"+
            "more"+
            "moreover"+
            "morning"+
            "mortgage"+
            "most"+
            "mostly"+
            "mother"+
            "motion"+
            "motivation"+
            "motor"+
            "mount"+
            "mountain"+
            "mouse"+
            "mouth"+
            "move"+
            "movement"+
            "movie"+
            "Mr"+
            "Mrs"+
            "Ms"+
            "much"+
            "multiple"+
            "murder"+
            "muscle"+
            "museum"+
            "music"+
            "musical"+
            "musician"+
            "Muslim"+
            "must"+
            "mutual"+
            "my"+
            "myself"+
            "mystery"+
            "myth"+
            "naked"+
            "name"+
            "narrative"+
            "narrow"+
            "nation"+
            "national"+
            "native"+
            "natural"+
            "naturally"+
            "nature"+
            "near"+
            "nearby"+
            "nearly"+
            "necessarily"+
            "necessary"+
            "neck"+
            "need"+
            "negative"+
            "negotiate"+
            "negotiation"+
            "neighbor"+
            "neighborhood"+
            "neither"+
            "nerve"+
            "nervous"+
            "net"+
            "network"+
            "never"+
            "nevertheless"+
            "new"+
            "newly"+
            "news"+
            "newspaper"+
            "next"+
            "nice"+
            "night"+
            "nine"+
            "no"+
            "nobody"+
            "nod"+
            "noise"+
            "nomination"+
            "none"+
            "nonetheless"+
            "nor"+
            "normal"+
            "normally"+
            "north"+
            "northern"+
            "nose"+
            "not"+
            "note"+
            "nothing"+
            "notice"+
            "notion"+
            "novel"+
            "now"+
            "nowhere"+
            "n't"+
            "nuclear"+
            "number"+
            "numerous"+
            "nurse"+
            "nut"+
            "object"+
            "objective"+
            "obligation"+
            "observation"+
            "observe"+
            "observer"+
            "obtain"+
            "obvious"+
            "obviously"+
            "occasion"+
            "occasionally"+
            "occupation"+
            "occupy"+
            "occur"+
            "ocean"+
            "odd"+
            "odds"+
            "of"+
            "off"+
            "offense"+
            "offensive"+
            "offer"+
            "office"+
            "officer"+
            "official"+
            "often"+
            "oh"+
            "oil"+
            "ok"+
            "okay"+
            "old"+
            "Olympic"+
            "on"+
            "once"+
            "one"+
            "ongoing"+
            "onion"+
            "online"+
            "only"+
            "onto"+
            "open"+
            "opening"+
            "operate"+
            "operating"+
            "operation"+
            "operator"+
            "opinion"+
            "opponent"+
            "opportunity"+
            "oppose"+
            "opposite"+
            "opposition"+
            "option"+
            "or"+
            "orange"+
            "order"+
            "ordinary"+
            "organic"+
            "organization"+
            "organize"+
            "orientation"+
            "origin"+
            "original"+
            "originally"+
            "other"+
            "others"+
            "otherwise"+
            "ought"+
            "our"+
            "ourselves"+
            "out"+
            "outcome"+
            "outside"+
            "oven"+
            "over"+
            "overall"+
            "overcome"+
            "overlook"+
            "owe"+
            "own"+
            "owner"+
            "pace"+
            "pack"+
            "package"+
            "page"+
            "pain"+
            "painful"+
            "paint"+
            "painter"+
            "painting"+
            "pair"+
            "pale"+
            "Palestinian"+
            "palm"+
            "pan"+
            "panel"+
            "pant"+
            "paper"+
            "parent"+
            "park"+
            "parking"+
            "part"+
            "participant"+
            "participate"+
            "participation"+
            "particular"+
            "particularly"+
            "partly"+
            "partner"+
            "partnership"+
            "party"+
            "pass"+
            "passage"+
            "passenger"+
            "passion"+
            "past"+
            "patch"+
            "path"+
            "patient"+
            "pattern"+
            "pause"+
            "pay"+
            "payment"+
            "PC"+
            "peace"+
            "peak"+
            "peer"+
            "penalty"+
            "people"+
            "pepper"+
            "per"+
            "perceive"+
            "percentage"+
            "perception"+
            "perfect"+
            "perfectly"+
            "perform"+
            "performance"+
            "perhaps"+
            "period"+
            "permanent"+
            "permission"+
            "permit"+
            "person"+
            "personal"+
            "personality"+
            "personally"+
            "personnel"+
            "perspective"+
            "persuade"+
            "pet"+
            "phase"+
            "phenomenon"+
            "philosophy"+
            "phone"+
            "photo"+
            "photograph"+
            "photographer"+
            "phrase"+
            "physical"+
            "physically"+
            "physician"+
            "piano"+
            "pick"+
            "picture"+
            "pie"+
            "piece"+
            "pile"+
            "pilot"+
            "pine"+
            "pink"+
            "pipe"+
            "pitch"+
            "place"+
            "plan"+
            "plane"+
            "planet"+
            "planning"+
            "plant"+
            "plastic"+
            "plate"+
            "platform"+
            "play"+
            "player"+
            "please"+
            "pleasure"+
            "plenty"+
            "plot"+
            "plus"+
            "PM"+
            "pocket"+
            "poem"+
            "poet"+
            "poetry"+
            "point"+
            "pole"+
            "police"+
            "policy"+
            "political"+
            "politically"+
            "politician"+
            "politics"+
            "poll"+
            "pollution"+
            "pool"+
            "poor"+
            "pop"+
            "popular"+
            "population"+
            "porch"+
            "port"+
            "portion"+
            "portrait"+
            "portray"+
            "pose"+
            "position"+
            "positive"+
            "possess"+
            "possibility"+
            "possible"+
            "possibly"+
            "post"+
            "pot"+
            "potato"+
            "potential"+
            "potentially"+
            "pound"+
            "pour"+
            "poverty"+
            "powder"+
            "power"+
            "powerful"+
            "practical"+
            "practice"+
            "pray"+
            "prayer"+
            "precisely"+
            "predict"+
            "prefer"+
            "preference"+
            "pregnancy"+
            "pregnant"+
            "preparation"+
            "prepare"+
            "prescription"+
            "presence"+
            "present"+
            "presentation"+
            "preserve"+
            "president"+
            "presidential"+
            "press"+
            "pressure"+
            "pretend"+
            "pretty"+
            "prevent"+
            "previous"+
            "previously"+
            "price"+
            "pride"+
            "priest"+
            "primarily"+
            "primary"+
            "prime"+
            "principal"+
            "principle"+
            "print"+
            "prior"+
            "priority"+
            "prison"+
            "prisoner"+
            "privacy"+
            "private"+
            "probably"+
            "problem"+
            "procedure"+
            "proceed"+
            "process"+
            "produce"+
            "producer"+
            "product"+
            "production"+
            "profession"+
            "professional"+
            "professor"+
            "profile"+
            "profit"+
            "program"+
            "progress"+
            "project"+
            "prominent"+
            "promise"+
            "promote"+
            "prompt"+
            "proof"+
            "proper"+
            "properly"+
            "property"+
            "proportion"+
            "proposal"+
            "propose"+
            "proposed"+
            "prosecutor"+
            "prospect"+
            "protect"+
            "protection"+
            "protein"+
            "protest"+
            "proud"+
            "prove"+
            "provide"+
            "provider"+
            "province"+
            "provision"+
            "psychological"+
            "psychologist"+
            "psychology"+
            "public"+
            "publication"+
            "publicly"+
            "publish"+
            "publisher"+
            "pull"+
            "punishment"+
            "purchase"+
            "pure"+
            "purpose"+
            "pursue"+
            "push"+
            "put"+"qualify"+
            "quality"+
            "quarter"+
            "quarterback"+
            "question"+
            "quick"+
            "quickly"+
            "quiet"+
            "quietly"+
            "quit"+
            "quite"+
            "quote"+
            "race"+
            "racial"+
            "radical"+
            "radio"+
            "rail"+
            "rain"+
            "raise"+
            "range"+
            "rank"+
            "rapid"+
            "rapidly"+
            "rare"+
            "rarely"+
            "rate"+
            "rather"+
            "rating"+
            "ratio"+
            "raw"+
            "reach"+
            "react"+
            "reaction"+
            "read"+
            "reader"+
            "reading"+
            "ready"+
            "real"+
            "reality"+
            "realize"+
            "really"+
            "reason"+
            "reasonable"+
            "recall"+
            "receive"+
            "recent"+
            "recently"+
            "recipe"+
            "recognition"+
            "recognize"+
            "recommend"+
            "recommendation"+
            "record"+
            "recording"+
            "recover"+
            "recovery"+
            "recruit"+
            "red"+
            "reduce"+
            "reduction"+
            "refer"+
            "reference"+
            "reflect"+
            "reflection"+
            "reform"+
            "refugee"+
            "refuse"+
            "regard"+
            "regarding"+
            "regardless"+
            "regime"+
            "region"+
            "regional"+
            "register"+
            "regular"+
            "regularly"+
            "regulate"+
            "regulation"+
            "reinforce"+
            "reject"+
            "relate"+
            "relation"+
            "relationship"+
            "relative"+
            "relatively"+
            "relax"+
            "release"+
            "relevant"+
            "relief"+
            "religion"+
            "religious"+
            "rely"+
            "remain"+
            "remaining"+
            "remarkable"+
            "remember"+
            "remind"+
            "remote"+
            "remove"+
            "repeat"+
            "repeatedly"+
            "replace"+
            "reply"+
            "report"+
            "reporter"+
            "represent"+
            "representation"+
            "representative"+
            "Republican"+
            "reputation"+
            "request"+
            "require"+
            "requirement"+
            "research"+
            "researcher"+
            "resemble"+
            "reservation"+
            "resident"+
            "resist"+
            "resistance"+
            "resolution"+
            "resolve"+
            "resort"+
            "resource"+
            "respect"+
            "respond"+
            "respondent"+
            "response"+
            "responsibility"+
            "responsible"+
            "rest"+
            "restaurant"+
            "restore"+
            "restriction"+
            "result"+
            "retain"+
            "retire"+
            "retirement"+
            "return"+
            "reveal"+
            "revenue"+
            "review"+
            "revolution"+
            "rhythm"+
            "rice"+
            "rich"+
            "rid"+
            "ride"+
            "rifle"+
            "right"+
            "ring"+
            "rise"+
            "risk"+
            "river"+
            "road"+
            "rock"+
            "role"+
            "roll"+
            "romantic"+
            "roof"+
            "room"+
            "root"+
            "rope"+
            "rose"+
            "rough"+
            "roughly"+
            "round"+
            "route"+
            "routine"+
            "row"+
            "rub"+
            "rule"+
            "run"+
            "running"+
            "rural"+
            "rush"+
            "Russian"+
            "sacred"+
            "sad"+
            "safe"+
            "safety"+
            "sake"+
            "salad"+
            "salary"+
            "sale"+
            "sales"+
            "salt"+
            "same"+
            "sample"+
            "sanction"+
            "sand"+
            "satellite"+
            "satisfaction"+
            "satisfy"+
            "sauce"+
            "save"+
            "saving"+
            "say"+
            "scale"+
            "scandal"+
            "scared"+
            "scenario"+
            "scene"+
            "schedule"+
            "scheme"+
            "scholar"+
            "scholarship"+
            "school"+
            "science"+
            "scientific"+
            "scientist"+
            "scope"+
            "score"+
            "scream"+
            "screen"+
            "script"+
            "sea"+
            "search"+
            "season"+
            "seat"+
            "second"+
            "secret"+
            "secretary"+
            "section"+
            "sector"+
            "secure"+
            "security"+
            "see"+
            "seed"+
            "seek"+
            "seem"+
            "segment"+
            "seize"+
            "select"+
            "selection"+
            "self"+
            "sell"+
            "Senate"+
            "senator"+
            "send"+
            "senior"+
            "sense"+
            "sensitive"+
            "sentence"+
            "separate"+
            "sequence"+
            "series"+
            "serious"+
            "seriously"+
            "serve"+
            "service"+
            "session"+
            "set"+
            "setting"+
            "settle"+
            "settlement"+
            "seven"+
            "several"+
            "severe"+
            "sex"+
            "sexual"+
            "shade"+
            "shadow"+
            "shake"+
            "shall"+
            "shape"+
            "share"+
            "sharp"+
            "she"+
            "sheet"+
            "shelf"+
            "shell"+
            "shelter"+
            "shift"+
            "shine"+
            "ship"+
            "shirt"+
            "shit"+
            "shock"+
            "shoe"+
            "shoot"+
            "shooting"+
            "shop"+
            "shopping"+
            "shore"+
            "short"+
            "shortly"+
            "shot"+
            "should"+
            "shoulder"+
            "shout"+
            "show"+
            "shower"+
            "shrug"+
            "shut"+
            "sick"+
            "side"+
            "sigh"+
            "sight"+
            "sign"+
            "signal"+
            "significance"+
            "significant"+
            "significantly"+
            "silence"+
            "silent"+
            "silver"+
            "similar"+
            "similarly"+
            "simple"+
            "simply"+
            "sin"+
            "since"+
            "sing"+
            "singer"+
            "single"+
            "sink"+
            "sir"+
            "sister"+
            "sit"+
            "site"+
            "situation"+
            "six"+
            "size"+
            "ski"+
            "skill"+
            "skin"+
            "sky"+
            "slave"+
            "sleep"+
            "slice"+
            "slide"+
            "slight"+
            "slightly"+
            "slip"+
            "slow"+
            "slowly"+
            "small"+
            "smart"+
            "smell"+
            "smile"+
            "smoke"+
            "smooth"+
            "snap"+
            "snow"+
            "so"+
            "so-called"+
            "soccer"+
            "social"+
            "society"+
            "soft"+
            "software"+
            "soil"+
            "solar"+
            "soldier"+
            "solid"+
            "solution"+
            "solve"+
            "some"+
            "somebody"+
            "somehow"+
            "someone"+
            "something"+
            "sometimes"+
            "somewhat"+
            "somewhere"+
            "son"+
            "song"+
            "soon"+
            "sophisticated"+
            "sorry"+
            "sort"+
            "soul"+
            "sound"+
            "soup"+
            "source"+
            "south"+
            "southern"+
            "Soviet"+
            "space"+
            "Spanish"+
            "speak"+
            "speaker"+
            "special"+
            "specialist"+
            "species"+
            "specific"+
            "specifically"+
            "speech"+
            "speed"+
            "spend"+
            "spending"+
            "spin"+
            "spirit"+
            "spiritual"+
            "split"+
            "spokesman"+
            "sport"+
            "spot"+
            "spread"+
            "spring"+
            "square"+
            "squeeze"+
            "stability"+
            "stable"+
            "staff"+
            "stage"+
            "stair"+
            "stake"+
            "stand"+
            "standard"+
            "standing"+
            "star"+
            "stare"+
            "start"+
            "state"+
            "statement"+
            "station"+
            "statistics"+
            "status"+
            "stay"+
            "steady"+
            "steal"+
            "steel"+
            "step"+
            "stick"+
            "still"+
            "stir"+
            "stock"+
            "stomach"+
            "stone"+
            "stop"+
            "storage"+
            "store"+
            "storm"+
            "story"+
            "straight"+
            "strange"+
            "stranger"+
            "strategic"+
            "strategy"+
            "stream"+
            "street"+
            "strength"+
            "strengthen"+
            "stress"+
            "stretch"+
            "strike"+
            "string"+
            "strip"+
            "stroke"+
            "strong"+
            "strongly"+
            "structure"+
            "struggle"+
            "student"+
            "studio"+
            "study"+
            "stuff"+
            "stupid"+
            "style"+
            "subject"+
            "submit"+
            "subsequent"+
            "substance"+
            "substantial"+
            "succeed"+
            "success"+
            "successful"+
            "successfully"+
            "such"+
            "sudden"+
            "suddenly"+
            "sue"+
            "suffer"+
            "sufficient"+
            "sugar"+
            "suggest"+
            "suggestion"+
            "suicide"+
            "suit"+
            "summer"+
            "summit"+
            "sun"+
            "super"+
            "supply"+
            "support"+
            "supporter"+
            "suppose"+
            "supposed"+
            "Supreme"+
            "sure"+
            "surely"+
            "surface"+
            "surgery"+
            "surprise"+
            "surprised"+
            "surprising"+
            "surprisingly"+
            "surround"+
            "survey"+
            "survival"+
            "survive"+
            "survivor"+
            "suspect"+
            "sustain"+
            "swear"+
            "sweep"+
            "sweet"+
            "swim"+
            "swing"+
            "switch"+
            "symbol"+
            "symptom"+
            "system"+
            "table"+
            "tablespoon"+
            "tactic"+
            "tail"+
            "take"+
            "tale"+
            "talent"+
            "talk"+
            "tall"+
            "tank"+
            "tap"+
            "tape"+
            "target"+
            "task"+
            "taste"+
            "tax"+
            "taxpayer"+
            "tea"+
            "teach"+
            "teacher"+
            "teaching"+
            "team"+
            "tear"+
            "teaspoon"+
            "technical"+
            "technique"+
            "technology"+
            "teen"+
            "teenager"+
            "telephone"+
            "telescope"+
            "television"+
            "tell"+
            "temperature"+
            "temporary"+
            "ten"+
            "tend"+
            "tendency"+
            "tennis"+
            "tension"+
            "tent"+
            "term"+
            "terms"+
            "terrible"+
            "territory"+
            "terror"+
            "terrorism"+
            "terrorist"+
            "test"+
            "testify"+
            "testimony"+
            "testing"+
            "text"+
            "than"+
            "thank"+
            "thanks"+
            "that"+
            "the"+
            "theater"+
            "their"+
            "them"+
            "theme"+
            "themselves"+
            "then"+
            "theory"+
            "therapy"+
            "there"+
            "therefore"+
            "these"+
            "they"+
            "thick"+
            "thin"+
            "thing"+
            "think"+
            "thinking"+
            "third"+
            "thirty"+
            "this"+
            "those"+
            "though"+
            "thought"+
            "thousand"+
            "threat"+
            "threaten"+
            "three"+
            "throat"+
            "through"+
            "throughout"+
            "throw"+
            "thus"+
            "ticket"+
            "tie"+
            "tight"+
            "time"+
            "tiny"+
            "tip"+
            "tire"+
            "tired"+
            "tissue"+
            "title"+
            "to"+
            "tobacco"+
            "today"+
            "toe"+
            "together"+
            "tomato"+
            "tomorrow"+
            "tone"+
            "tongue"+
            "tonight"+
            "too"+
            "tool"+
            "tooth"+
            "top"+
            "topic"+
            "toss"+
            "total"+
            "totally"+
            "touch"+
            "tough"+
            "tour"+
            "tourist"+
            "tournament"+
            "toward"+
            "towards"+
            "tower"+
            "town"+
            "toy"+
            "trace"+
            "track"+
            "trade"+
            "tradition"+
            "traditional"+
            "traffic"+
            "tragedy"+
            "trail"+
            "train"+
            "training"+
            "transfer"+
            "transform"+
            "transformation"+
            "transition"+
            "translate"+
            "transportation"+
            "travel"+
            "treat"+
            "treatment"+
            "treaty"+
            "tree"+
            "tremendous"+
            "trend"+
            "trial"+
            "tribe"+
            "trick"+
            "trip"+
            "troop"+
            "trouble"+
            "truck"+
            "true"+
            "truly"+
            "trust"+
            "truth"+
            "try"+
            "tube"+
            "tunnel"+
            "turn"+
            "TV"+
            "twelve"+
            "twenty"+
            "twice"+
            "twin"+
            "two"+
            "type"+
            "typical"+
            "typically"+
            "ugly"+
            "ultimate"+
            "ultimately"+
            "unable"+
            "uncle"+
            "under"+
            "undergo"+
            "understand"+
            "understanding"+
            "unfortunately"+
            "uniform"+
            "union"+
            "unique"+
            "unit"+
            "United"+
            "universal"+
            "universe"+
            "university"+
            "unknown"+
            "unless"+
            "unlike"+
            "unlikely"+
            "until"+
            "unusual"+
            "up"+
            "upon"+
            "upper"+
            "urban"+
            "urge"+
            "us"+
            "use"+
            "used"+
            "useful"+
            "user"+
            "usual"+
            "usually"+
            "utility"+
            "vacation"+
            "valley"+
            "valuable"+
            "value"+
            "variable"+
            "variation"+
            "variety"+
            "various"+
            "vary"+
            "vast"+
            "vegetable"+
            "vehicle"+
            "venture"+
            "version"+
            "versus"+
            "very"+
            "vessel"+
            "veteran"+
            "via"+
            "victim"+
            "victory"+
            "video"+
            "view"+
            "viewer"+
            "village"+
            "violate"+
            "violation"+
            "violence"+
            "violent"+
            "virtually"+
            "virtue"+
            "virus"+
            "visible"+
            "vision"+
            "visit"+
            "visitor"+
            "visual"+
            "vital"+
            "voice"+
            "volume"+
            "volunteer"+
            "vote"+
            "voter"+
            "vs"+
            "vulnerable"+
            "wage"+
            "wait"+
            "wake"+
            "walk"+
            "wall"+
            "wander"+
            "want"+
            "war"+
            "warm"+
            "warn"+
            "warning"+
            "wash"+
            "waste"+
            "watch"+
            "water"+
            "wave"+
            "way"+
            "we"+
            "weak"+
            "wealth"+
            "wealthy"+
            "weapon"+
            "wear"+
            "weather"+
            "wedding"+
            "week"+
            "weekend"+
            "weekly"+
            "weigh"+
            "weight"+
            "welcome"+
            "welfare"+
            "well"+
            "west"+
            "western"+
            "wet"+
            "what"+
            "whatever"+
            "wheel"+
            "when"+
            "whenever"+
            "where"+
            "whereas"+
            "whether"+
            "which"+
            "while"+
            "whisper"+
            "white"+
            "who"+
            "whole"+
            "whom"+
            "whose"+
            "why"+
            "wide"+
            "widely"+
            "widespread"+
            "wife"+
            "wild"+
            "will"+
            "willing"+
            "win"+
            "wind"+
            "window"+
            "wine"+
            "wing"+
            "winner"+
            "winter"+
            "wipe"+
            "wire"+
            "wisdom"+
            "wise"+
            "wish"+
            "with"+
            "withdraw"+
            "within"+
            "without"+
            "witness"+
            "woman"+
            "wonder"+
            "wonderful"+
            "wood"+
            "wooden"+
            "word"+
            "work"+
            "worker"+
            "working"+
            "works"+
            "workshop"+
            "world"+
            "worried"+
            "worry"+
            "worth"+
            "would"+
            "wound"+
            "wrap"+
            "write"+
            "writer"+
            "writing"+
            "wrong"+
            "yard"+
            "yeah"+
            "year"+
            "yell"+"yesterday"+
            "yet"+
            "yield"+
            "you"+
            "young"+
            "your"+
            "yours"+
            "yourself"+
            "youth"+
            "zone";

    public final String intermediate_data = "Nice to meet you$" + "Please call me.$" + "Be careful.$" + "Be careful driving.$" + "Can you translate this for me?$" +
            "Chicago is very different from Boston.$" + "Don't worry.$" + "Everyone knows it.$" + "Everything is ready.$" + "Excellent.$" + "From time to time.$" + "Good idea.$" + "He likes it very much.$" + "Help!$" + "He's coming soon.$" + "He's right.$" + "He's very annoying.$" + "He's very famous.$" + "How are you?$" +
            "How's work going?$" + "Hurry!$" + "I ate already.$" + "I can't hear you.$" + "I'd like to go for a walk.$" + "I don't know how to use it.$" +
            "I don't like him.$" + "I don't like it.$" + "I don't speak very well.$" + "I don't understand.$" + "I don't want it.$" + "I don't want that.$" +
            "I don't want to bother you.$" + "I feel good.$" + "If you need my help, please let me know.$" + "I get off of work at 6.$" + "I have a headache.$" +
            "I hope you and your wife have a nice trip.$" + "I know.$" + "I like her.$" + "I'll call you when I leave.$" + "I'll come back later.$" +
            "I'll pay.$" + "I'll take it.$" + "I'll take you to the bus stop.$" + "I lost my watch.$" + "I love you.$" + "I'm an Indian.$" + "I'm cleaning my room.$" +
            "I'm cold.$" + "I'm coming to pick you up.$" + "I'm going to leave.$" + "I'm good, and you?$" +
            "I'm happy.$" + "I'm hungry.$" + "I'm married.$" + "I'm not busy.$" + "I'm not married.$" + "I'm not ready yet.$" + "I'm not sure.$" + "I'm sorry, we're sold out.$" + "I'm thirsty.$" +
            "I'm very busy. I don't have time now.$" + "I need to change clothes.$" +
            "I need to go home.$" + "I only want a snack.$" + "Is Mr. Smith an American?$" + "Is that enough?$" + "I think it's very good.$" + "I think it tastes good.$" +
            "I thought the clothes were cheaper.$" + "It's longer than 2 miles.$" +
            "I've been here for two days.$" + "I've heard Texas is a beautiful place.$" + "I've never seen that before.$" + "I was about to leave the restaurant when my friends arrived.$" + "Just a little.$" +
            "Just a moment.$" + "Let me check.$" + "Let me think about it.$" + "Let's go have a look.$" + "Let's practice English.$" + "May I speak to Mrs. Smith please?$" + "More than that.$" + "Never mind.$" + "Next time.$" +
            "No.$" + "Nonsense.$" + "No, thank you.$" + "Nothing else.$" + "Not recently.$" + "Not yet.$" + "Of course.$" + "Okay.$" + "Please fill out this form.$" +
            "Please take me to this address.$" + "Please write it down.$" + "Really?$" + "Right here.$" + "Right there.$" + "See you later.$" + "See you tomorrow.$" +
            "See you tonight.$" + "She's pretty.$" + "Sorry to bother you.$" + "Stop!$" + "Take a chance.$" + "Take it outside.$" + "Tell me.$" + "Thanks for everything.$" +
            "Thanks for your help.$" + "Thank you.$" + "Thank you miss.$" + "Thank you sir.$" + "Thank you very much.$" + "That looks great.$" + "That's alright.$" + "That's enough.$" +
            "That's fine.$" + "That's it.$" + "That smells bad.$" + "That's not fair.$" + "That's not right.$" + "That's right.$" + "That's too bad.$" +
            "That's too many.$" + "That's too much.$" + "The book is under the table.$" + "They'll be right back.$" + "They're the same.$" + "They're very busy.$" +
            "This doesn't work.$" + "This is very difficult.$" + "This is very important.$" + "Try it.$" + "Very good, thanks.$" + "We like it very much.$" +
            "Would you take a message please?$" + "Yes, really.$" + "You're beautiful.$" + "You're very nice.$" + "You're very smart.$" + "Your things are all here.$";

    public final String hard_data = "The Moon is a barren, rocky world without air and water.$" +
            " It has dark lava plain on its surface.$" +
            " The Moon is filled wit craters.$" +
            " It has no light of its own.$" +
            " It gets its light from the Sun.$" +
            " The Moon keeps changing its shape as it moves round the Earth.$" +
            " It spins on its axis in 27.3 days$" +
            " Edwin Aldrin were the first ones to set their foot on the Moon on 21 July 1969.$" +
            " They reached the Moon in their space craft named Apollo II.$" +
            " The sun is a huge ball of gases.$" +
            " It has a diameter of 1,392,000 km.$" +
            " It is so huge that it can hold millions of planets inside it.$" +
            " The Sun is mainly made up of hydrogen and helium gas.$" +
            " The surface of the Sun is known as the photosphere.$" +
            " The photosphere is surrounded by a thin layer of gas known as the chromospheres.$" +
            " Without the Sun, there would be no life on Earth.$" +
            " There would be no plants, no animals and no human beings.$" +
            " As, all the living things on Earth get their energy from the Sun for their survival.$" +
            " The Solar System consists of the Sun Moon and Planets.$" +
            " It also consists of comets, meteoroids and asteroids.$ The Sun is the largest member of the Solar System.$"+
            " The Mahabharata is a story about a great battle between the Kauravas and the Pandavas.$" +
            " The battle was fought in Kurukshetra near Delhi.$" +
            " Many kings and princes took part in the battle.$" +
            " The Pandavas defeated the Kauravas.$" +
            " The Bhagvad Gita is a holy book of the Hindus.$" +
            " It is a part of the Mahabharata.$" +
            " It is a book of collection of teachings of Lord Krishna to Arjuna in the battlefield.$" +
            " It is the longest epic in the world.$" +
            " The Ramayana is a story of Lord Rama written by the SageValmiki.$" +
            " Lord Rama, the prince of Ayodhya, in order to help his father Dasharatha went to exile for fourteen years.$" +
            " His wife, Sita and his younger brother Lakshmana also went with him.$" +
            " He went through many difficulties in the forest. One day Ravana, the king of Lanka carried away Sita with him.$" +
            " Then, Lord Rama, with the help of Hanumana, defeated and killed Ravana;$" +
            " Sita, Rama and Lakshmana returned to Ayodhya after their exile.$" +
            " It is situated on the banks of river Yamuna at Agra.$" +
            " It looks beautiful in the moonlight.$" +
            " The Taj Mahal is made up of white marble.$" +
            " In front of the monument, there is a beautiful garden known as the Charbagh.$" +
            " Inside the monument, there are two tombs.$" +
            " These tombs are of Shah Jahan and his wife Mumtaz Mahal.$" +
            " The Taj Mahal is considered as one of the Seven Wonders of the World.$" +
            " Many tourists come to see this beautiful structure from different parts of the world.$" +
            " Delhi is the capital of India.$" +
            " It is situated on the banks of the river Yamuna.$" +
            " It is surrounded by Haryanaand Uttar Pradesh.$" +
            " Some of the monuments are hundreds of years old.$" +
            " Apart from this, there is the Parliament House, the Central Secretariat and the famous Connaught place.$" +
            " Delhi is a beautiful city.$" +
            " But, it is becoming very crowded and polluted.$" +
            " I love Delhi a lot.$" +
            " A snake charmer is a person who moves the streets with different types of the banks of the river Yamuna.$" +
            " It is snakes in his basket.$" +
            " He goes from one place to another to show various types of snakes and their tricks.$" +
            " He carries a pipe with which he plays music and snakes dance to his tune.$" +
            " He usually wears a colourful dress.$" +
            " The job of a snake charmer is quite dangerous.$" +
            " Some snakes are quite poisonous and can even bite him.$" +
            " It is not an easy task to catch and train them for the shows.$" +
            " A street beggar can be seen everywhere; at the bus stop, railway stations, religious places, markets etc.$" +
            " Some beggars are crippled, lame and some are blind.$" +
            " They are unable to earn their livelihood.$" +
            " Whereas some are healthy and they do not deserve our sympathy.$" +
            " We should see that they take up some profession.$" +
            " They should not be allowed to beg.$" +
            " On my way to school I see a beggar daily.$" +
            " He wears old rags.$" +
            " He is partially blind.$" +
            " I feel pity seeing him but I can’t help it I can only pray to God to help him to earn his livelihood.$" +
            " The doctor is a person who looks after the sick people and prescribes medicines so that the patient recovers fast.$" +
            " In order to become a doctor, a person has to study medicine.$" +
            " Doctors lead a hard life.$" +
            " Their life is very busy.$" +
            " They get up early in the morning and go to the hospital.$" +
            " They work without taking a break.$" +
            " They always remain polite so that patients feel comfortable with them.$" +
            " Since doctors work so hard we must realise their value.$" +
            " A hawker is a person who moves from one place to another and sell their goods, by shouting on the streets.$" +
            " They work hard throughout the day.$" +
            " They move on the street on their bicycle and sometimes on foot and sell their products.$" +
            " We can see hawkers everywhere.$" +
            " They move everywhere selling their goods without caring about the weather.$" +
            " There is a hawker who sells vegetables on his bicycle in our locality.$" +
            " His name is Manoj.$" +
            " He brings fresh vegetables at a very reasonable price.$" +
            " He is a nice and an honest hawker.$" +
            " India is an agricultural country.$" +
            " Most of the people live in villages and are farmers.$" +
            " They grow cereals, pulses, vegetables and fruits.$" +
            " The farmers lead a tough life.$" +
            " They get up early in the morning and go to the fields.$" +
            " They stay and work on the farm late till evening.$" +
            " The farmers usually live in kuchcha houses.$" +
            " Though, they work hard they remain poor.$" +
            " Farmers eat simple food; wear simple clothes and rear animals like cows, buffaloes and oxen.$" +
            " Without them there would be no cereals for us to eat.$" +
            " They play an important role in the growth and economy of a country.$";

    public String[] sentences_array(int i) {
        StringTokenizer st;
        if (i == 1) {
            st = new StringTokenizer(basic_data, "$");
        } else if (i == 2) {
            st = new StringTokenizer(intermediate_data, "$");
        } else {
            st = new StringTokenizer(hard_data, "$");
        }
        int n = st.countTokens();
        String[] sentences = new String[n];
        int j = 0;
        while (st.hasMoreTokens()) {
            sentences[j] = st.nextToken();
            j++;
        }
        return sentences;
    }
}
